
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getAppInfo() : Promise<AppInfoDto> {
    return await TAURI_INVOKE("get_app_info");
},
async showMainWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_main_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showCatWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_cat_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showSettingsWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_settings_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showActivityWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_activity_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showActivityWindowAtSession(sessionId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_activity_window_at_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showSettingsWindowAtProfile(profileId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_settings_window_at_profile", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideMainWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_main_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideCatWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_cat_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideSettingsWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_settings_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideActivityWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_activity_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideBlockerWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_blocker_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restartApp() : Promise<void> {
    await TAURI_INVOKE("restart_app");
},
async quitApp() : Promise<void> {
    await TAURI_INVOKE("quit_app");
},
async installUpdate() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<AppSettings> {
    return await TAURI_INVOKE("get_settings");
},
async setSettings(settings: AppSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearHistory() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetSettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDataDirectoryPath() : Promise<string> {
    return await TAURI_INVOKE("get_data_directory_path");
},
async openDataDirectory() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_data_directory") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTimer() : Promise<TimerDto> {
    return await TAURI_INVOKE("get_timer");
},
async startTimer(intention: string | null, profileIds: number[] | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_timer", { intention, profileIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseTimer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeTimer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetTimer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Complete the current session and advance to the next in the Pomodoro sequence (work↔break).
 * When the next session is work, intention and profile_ids may be provided.
 */
async advancePomodoroTimer(intention: string | null, profileIds: number[] | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("advance_pomodoro_timer", { intention, profileIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Advance to the specified next Progressive session type and duration.
 */
async advanceProgressiveTimer(sessionType: ProgressiveSessionType, durationSeconds: number, intention: string | null, profileIds: number[] | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("advance_progressive_timer", { sessionType, durationSeconds, intention, profileIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Complete the current session and reset timer.
 * Like reset, but marks session as completed instead of cancelled.
 */
async completeTimer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("complete_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTimerDuration(minutes: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_timer_duration", { minutes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get current active app or window by querying the OS.
 */
async getCurrentActivity(params: GetCurrentActivityParams) : Promise<Result<CurrentActivityDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_activity", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get past activities within a time range.
 * Returns window-level activities if available, otherwise falls back to app-level activities.
 */
async getWindowActivities(params: GetWindowActivitiesParams) : Promise<Result<WindowActivityDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_window_activities", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTodayFocusSeconds() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_today_focus_seconds") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSessions(startedAfter: number, startedBefore: number, limit: number | null, minDurationSecs: number | null) : Promise<Result<SessionSummaryDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sessions", { startedAfter, startedBefore, limit, minDurationSecs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMostRecentSessionId(startedAfter: number, startedBefore: number, minDurationSecs: number | null) : Promise<Result<number | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_most_recent_session_id", { startedAfter, startedBefore, minDurationSecs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSession(sessionId: number) : Promise<Result<SessionDetailDto | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the most recent completed work session.
 */
async getLastWorkSession(minDurationSecs: number | null) : Promise<Result<SessionDetailDto | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_last_work_session", { minDurationSecs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if accessibility permission is granted.
 */
async isAccessibilityGranted() : Promise<boolean> {
    return await TAURI_INVOKE("is_accessibility_granted");
},
/**
 * Open System Settings to Accessibility pane.
 */
async openAccessibilitySettings() : Promise<void> {
    await TAURI_INVOKE("open_accessibility_settings");
},
/**
 * Check if input monitoring permission is granted.
 */
async isInputMonitoringGranted() : Promise<boolean> {
    return await TAURI_INVOKE("is_input_monitoring_granted");
},
/**
 * Open System Settings to Input Monitoring pane.
 */
async openInputMonitoringSettings() : Promise<void> {
    await TAURI_INVOKE("open_input_monitoring_settings");
},
/**
 * Search for apps and websites.
 */
async search(params: SearchParams) : Promise<Result<SearchResultDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Refresh the search cache (reloads apps from system).
 */
async refreshSearchCache() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_search_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Play a sound effect.
 */
async playSound(id: SoundId) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("play_sound", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFocusProfiles() : Promise<Result<FocusProfileDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_focus_profiles") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFocusProfile(id: number) : Promise<Result<FocusProfileDto | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_focus_profile", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFocusProfile(name: string, color: string | null, enabled: boolean, categories: FocusProfileCategoryParams[], activations: FocusProfileActivationParams[]) : Promise<Result<FocusProfileDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_focus_profile", { name, color, enabled, categories, activations }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateFocusProfile(id: number, name: string, color: string | null, enabled: boolean, categories: FocusProfileCategoryParams[], activations: FocusProfileActivationParams[]) : Promise<Result<FocusProfileDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_focus_profile", { id, name, color, enabled, categories, activations }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteFocusProfile(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_focus_profile", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns all enabled profiles with their activation status for session setup.
 * 
 * - AlwaysOn: active always_on activation — shown, not removable
 * - PreSelected: active pre_selected activation — shown, removable
 * - Manual: no active activation — user adds manually
 * 
 * `session_type`: None = no session type filter, show all.
 */
async getSessionProfiles(sessionType: FocusSessionType | null) : Promise<Result<SessionProfileDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session_profiles", { sessionType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns profiles currently active based on their always_on activation rules and the
 * current session type from TimerState.
 */
async getActiveFocusProfiles() : Promise<Result<FocusProfileDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_active_focus_profiles") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Current blocking violation (None if nothing is blocked).
 */
async getBlockingViolation() : Promise<BlockingViolationDto | null> {
    return await TAURI_INVOKE("get_blocking_violation");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
appSettingsChangedEvent: AppSettingsChangedEvent,
blockingViolationEvent: BlockingViolationEvent,
currentActivityEvent: CurrentActivityEvent,
inputDetectedEvent: InputDetectedEvent,
profileChangedEvent: ProfileChangedEvent,
sessionChangedEvent: SessionChangedEvent,
sessionCompletedEvent: SessionCompletedEvent,
timerUpdatedEvent: TimerUpdatedEvent,
updateAvailableEvent: UpdateAvailableEvent
}>({
appSettingsChangedEvent: "app-settings-changed-event",
blockingViolationEvent: "blocking-violation-event",
currentActivityEvent: "current-activity-event",
inputDetectedEvent: "input-detected-event",
profileChangedEvent: "profile-changed-event",
sessionChangedEvent: "session-changed-event",
sessionCompletedEvent: "session-completed-event",
timerUpdatedEvent: "timer-updated-event",
updateAvailableEvent: "update-available-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Activation mode for a focus profile activation rule.
 */
export type ActivationMode = "always_on" | "pre_selected"
export type ActivitySettings = { 
/**
 * Whether to record app usage (app switches)
 */
trackApps: boolean; 
/**
 * Whether to track window changes (not just app switches)
 */
trackWindows: boolean; 
/**
 * Whether to track browser URLs
 */
trackBrowser: boolean }
/**
 * An installed application.
 */
export type App = { 
/**
 * Unique identifier (same as bundle_id).
 */
id: string; bundleId: string; name: string | null; icon: string | null; color: string | null }
export type AppDistribution = "direct" | "appStore"
/**
 * App icon with brand color.
 */
export type AppIcon = { 
/**
 * Icon as base64 PNG data URL
 */
dataUrl: string | null; 
/**
 * Brand color as hex string like "#5865F2"
 */
color: string | null }
export type AppInfo = { 
/**
 * Process ID
 */
pid: number; 
/**
 * Application name (localized)
 */
name: string | null; 
/**
 * Bundle identifier (macOS)
 */
bundleId: string | null; 
/**
 * Path to the executable
 */
processPath: string | null; 
/**
 * App icon and brand color (only populated if `include_app_icon` is enabled)
 */
icon: AppIcon | null }
export type AppInfoDto = { version: string; stage: Stage; distribution: AppDistribution }
export type AppSettings = { version: SettingsVersion; launchAtLogin: boolean; features: FeaturesSettings; appearance: AppearanceSettings; audio: AudioSettings; developer: DeveloperSettings; timer: TimerSettings; goals: GoalSettings; activity: ActivitySettings; cat: CatSettings; focus: FocusSettings }
export type AppSettingsChangedEvent = AppSettings
export type AppearanceSettings = { theme: Theme }
export type AudioChannelSettings = { enabled: boolean; 
/**
 * Volume 0.0..=1.0 (linear scale)
 */
volume: number }
export type AudioSettings = { session: AudioChannelSettings; sessionEnd: AudioChannelSettings; effects: AudioChannelSettings }
/**
 * Which category and above gets blocked when a focus profile is active.
 */
export type BlockThreshold = 
/**
 * Block only Distracting apps/websites.
 */
"distracting" | 
/**
 * Block Neutral and Distracting apps/websites.
 */
"neutral"
/**
 * The target that was blocked.
 */
export type BlockedTargetDto = { type: "app"; bundleId: string } | { type: "website"; domain: string }
/**
 * Describes what was blocked and by which profile.
 * Profile fields are None when blocked by threshold with no explicit category assignment.
 */
export type BlockingViolationDto = { profileId: number | null; profileName: string | null; profileColor: string | null; blockedTarget: BlockedTargetDto }
/**
 * Event emitted when a blocking violation is detected (or cleared).
 */
export type BlockingViolationEvent = BlockingViolationDto | null
export type BrowserInfo = { 
/**
 * Current URL of the active tab.
 */
url: string | null; 
/**
 * Whether the window is in private/incognito mode.
 * 
 * - `None` if detection failed or not supported
 * - `Some(true)` if private mode is active
 * - `Some(false)` if private mode is not active
 */
isPrivate: boolean | null; 
/**
 * Website information (only populated if `include_website_info` is enabled in config)
 */
website: WebsiteInfo | null }
export type CatSettings = { equippedFur: string; equippedFace: string; equippedHat: string | null }
/**
 * A category assignment within a focus profile (target + category).
 */
export type CategoryAssignmentDto = { id: number; category: FocusCategory; target: FocusTargetDto }
export type CountdownSettings = { durationMinutes: number }
export type CurrentActivityDto = { appActivated: { app: AppInfo } } | { windowChanged: { window: WindowInfo } }
export type CurrentActivityEvent = CurrentActivityDto
export type CurrentActivityPollTarget = "app" | "window"
export type DeveloperSettings = { cat: boolean; timerSpeed: number }
export type FeaturesSettings = { goals: boolean; activity: boolean; profiles: boolean; catWindow: boolean; developer: boolean }
/**
 * Focus category for an app or website within a profile.
 */
export type FocusCategory = "focused" | "neutral" | "distracting"
/**
 * An activation rule for a focus profile.
 * session_types: None = all session types; Some([...]) = restricted to listed types.
 * schedule_*: None = no time restriction; Some = AND condition with session_types.
 */
export type FocusProfileActivationDto = { id: number; mode: ActivationMode; sessionTypes: FocusSessionType[] | null; scheduleDays: number[] | null; scheduleStartTime: string | null; scheduleEndTime: string | null }
export type FocusProfileActivationParams = { mode: ActivationMode; sessionTypes: FocusSessionType[] | null; scheduleDays: number[] | null; scheduleStartTime: string | null; scheduleEndTime: string | null }
export type FocusProfileCategoryParams = { category: FocusCategory; target: FocusTargetDto }
/**
 * Focus profile with its category assignments and activation rules.
 */
export type FocusProfileDto = { id: number; name: string; color: string | null; enabled: boolean; categories: CategoryAssignmentDto[]; activations: FocusProfileActivationDto[]; createdAt: number }
/**
 * Session type for focus profile activation filtering.
 * Focus = any focus/work session (pomodoro work, progressive work, countdown).
 * Break = any rest session (pomodoro breaks, progressive break).
 */
export type FocusSessionType = "Focus" | "Break"
export type FocusSettings = { blockThreshold: BlockThreshold }
/**
 * The target of a category assignment: all, a specific app, or a specific website.
 */
export type FocusTargetDto = { type: "all" } | { type: "app"; bundle_id: string; name: string | null; icon: string | null; color: string | null } | { type: "website"; domain: string; name: string | null; icon: string | null; color: string | null }
export type GetCurrentActivityParams = { pollTarget: CurrentActivityPollTarget }
export type GetWindowActivitiesParams = { startedAfter: number; startedBefore: number; limit: number | null }
export type GoalSettings = { 
/**
 * Daily focus goal in minutes (default: 120 = 2h)
 */
dailyGoalMinutes: number }
export type GroupMemberDto = { type: "app"; app: App } | { type: "website"; website: Website }
/**
 * Event emitted when user input is detected (throttled).
 */
export type InputDetectedEvent = InputType
/**
 * Type of input event detected.
 */
export type InputType = "keyboard" | "mouse"
export type PomodoroSettings = { workDurationMinutes: number; shortBreakMinutes: number; longBreakMinutes: number; sessionsBeforeLongBreak: number; autoAdvance: boolean; autoAdvanceCountdownSeconds: number; showSessionSetup: boolean }
/**
 * How a profile was activated for session selection.
 */
export type ProfileActivation = 
/**
 * Always-on activation is active, shown in session setup, not removable.
 */
"always_on" | 
/**
 * Pre-selected by activation rule, shown in session setup, removable.
 */
"pre_selected" | 
/**
 * Manually added by the user.
 */
"manual"
/**
 * Event emitted when a focus profile is created, updated, or deleted.
 */
export type ProfileChangedEvent = null
export type ProgressivePomodoroSettings = { ratings: ProgressiveRatingSetting[]; autoAdvance: boolean; autoAdvanceCountdownSeconds: number; showSessionSetup: boolean }
export type ProgressiveRatingSetting = { key: string; label: string; description: string; suggestions: ProgressiveSuggestion[] }
export type ProgressiveSessionType = "Work" | "Break"
export type ProgressiveSuggestion = { workMinutes: number; breakMinutes: number | null }
export type SearchParams = { 
/**
 * Search query
 */
query: string; 
/**
 * Include installed apps (default: true)
 */
includeApps?: boolean; 
/**
 * Include websites (default: true)
 */
includeWebsites?: boolean; 
/**
 * Include icons - slower (default: false)
 */
includeIcons?: boolean; 
/**
 * Maximum results (default: 20)
 */
limit: number | null }
export type SearchResultDto = { type: "app"; app: App; score: number } | { type: "website"; website: Website; score: number } | { type: "group"; name: string; icon: string | null; members: GroupMemberDto[]; score: number }
/**
 * Event emitted when session state changes (started, completed, cancelled).
 */
export type SessionChangedEvent = null
/**
 * Event emitted when a session is completed.
 */
export type SessionCompletedEvent = SessionSummaryDto
export type SessionDetailDto = { id: number; sessionType: string; status: SessionStatus; plannedSeconds: number; actualSeconds: number | null; intention: string | null; startedAt: number; endedAt: number | null; events: SessionEventDto[]; stats: SessionStatsDto }
export type SessionEventDataDto = { seconds: number | null }
export type SessionEventDto = { eventType: string; timestamp: number; 
/**
 * Extra data (e.g., seconds for Extended events)
 */
data: SessionEventDataDto | null }
/**
 * A profile shown in session setup, with how it was activated.
 */
export type SessionProfileDto = { profile: FocusProfileDto; activation: ProfileActivation }
/**
 * Computed stats for a session.
 */
export type SessionStatsDto = { pausedSeconds: number; extendedSeconds: number; overtimeSeconds: number }
export type SessionStatus = "active" | "completed" | "cancelled"
export type SessionSummaryDto = { id: number; sessionType: string; status: SessionStatus; plannedSeconds: number; actualSeconds: number | null; intention: string | null; startedAt: number; endedAt: number | null }
export type SettingsVersion = "0.0.1" | "0.0.2"
export type SoundId = "tick" | "complete" | "meow" | "wind-up-tick-1" | "wind-up-tick-2" | "wind-up-tick-3" | "wind-up-tick-4" | "wind-up-tick-5" | "wind-up-tick-6" | "wind-up-tick-7" | "wind-up-tick-8" | "wind-up-tick-9" | "wind-up-tick-10" | "wind-up-tick-11"
export type Stage = "dev" | "prod"
export type Theme = "light" | "dark" | "auto"
export type TimerDto = { status: TimerStatus; sessionType: string; totalSeconds: number; remainingSeconds: number; overtimeSeconds: number; sessionsCompleted: number }
export type TimerModeEnum = "pomodoro" | "progressive" | "countdown"
export type TimerSettings = { timerMode: TimerModeEnum; pomodoro: PomodoroSettings; progressive: ProgressivePomodoroSettings; countdown: CountdownSettings }
export type TimerStatus = "idle" | "running" | "paused"
export type TimerUpdatedEvent = TimerDto
export type UpdateAvailableEvent = UpdateInfo
export type UpdateInfo = { version: string; currentVersion: string; 
/**
 * Semver parts we are behind (e.g. 1.2.3 → 2.0.0 gives 1, 0, 0).
 */
majorBehind: number; minorBehind: number; patchBehind: number }
/**
 * A website identified by domain.
 */
export type Website = { 
/**
 * Unique identifier (same as domain).
 */
id: string; domain: string; name: string | null; icon: string | null; color: string | null }
export type WebsiteInfo = { 
/**
 * Domain extracted from the browser URL (e.g., "github.com")
 */
domain: string; 
/**
 * Favicon as base64 PNG data URL (e.g., "data:image/png;base64,...")
 */
favicon: string | null; 
/**
 * Dominant color extracted from favicon as hex string (e.g., "#FF5733")
 */
color: string | null }
export type WindowActivityDto = { appBundleId: string | null; appName: string | null; appIcon: string | null; appColor: string | null; websiteDomain: string | null; websiteName: string | null; websiteIcon: string | null; websiteColor: string | null; windowTitle: string | null; browserUrl: string | null; startedAt: number; endedAt: number }
export type WindowBounds = { 
/**
 * X coordinate (left edge)
 */
x: number; 
/**
 * Y coordinate (top edge)
 */
y: number; 
/**
 * Window width
 */
width: number; 
/**
 * Window height
 */
height: number }
export type WindowInfo = { 
/**
 * Window title
 */
title: string | null; 
/**
 * Platform-specific window identifier
 */
windowId: number | null; 
/**
 * Window position and size
 */
bounds: WindowBounds | null; 
/**
 * Application information
 */
app: AppInfo; 
/**
 * Browser information (only populated if `include_browser_info` is enabled in config)
 */
browser: BrowserInfo | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
