
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getAppInfo() : Promise<AppInfo> {
    return await TAURI_INVOKE("get_app_info");
},
async showMainWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_main_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showCatWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_cat_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showSettingsWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_settings_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showHistoryWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_history_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideMainWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_main_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideCatWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_cat_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideSettingsWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_settings_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideHistoryWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_history_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async quitApp() : Promise<void> {
    await TAURI_INVOKE("quit_app");
},
async getSettings() : Promise<AppSettings> {
    return await TAURI_INVOKE("get_settings");
},
async setSettings(settings: AppSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDataDirectoryPath() : Promise<string> {
    return await TAURI_INVOKE("get_data_directory_path");
},
async openDataDirectory() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_data_directory") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTimer() : Promise<Timer> {
    return await TAURI_INVOKE("get_timer");
},
async startTimer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseTimer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeTimer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetTimer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async skipTimer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("skip_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTimerDuration(minutes: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_timer_duration", { minutes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get window activities within a time range.
 */
async getWindowActivities(params: GetWindowActivitiesParams) : Promise<Result<WindowActivityDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_window_activities", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTodayFocusSeconds() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_today_focus_seconds") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSessions(startedAfter: number, startedBefore: number, limit: number | null) : Promise<Result<SessionSummaryDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sessions", { startedAfter, startedBefore, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSession(sessionId: number) : Promise<Result<SessionDetailDto | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if accessibility permission is granted.
 */
async isAccessibilityGranted() : Promise<boolean> {
    return await TAURI_INVOKE("is_accessibility_granted");
},
/**
 * Open System Settings to Accessibility pane.
 */
async openAccessibilitySettings() : Promise<void> {
    await TAURI_INVOKE("open_accessibility_settings");
},
/**
 * Check if input monitoring permission is granted.
 */
async isInputMonitoringGranted() : Promise<boolean> {
    return await TAURI_INVOKE("is_input_monitoring_granted");
},
/**
 * Open System Settings to Input Monitoring pane.
 */
async openInputMonitoringSettings() : Promise<void> {
    await TAURI_INVOKE("open_input_monitoring_settings");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
appSettingsChangedEvent: AppSettingsChangedEvent,
inputDetectedEvent: InputDetectedEvent,
timerCompleteEvent: TimerCompleteEvent,
timerUpdatedEvent: TimerUpdatedEvent
}>({
appSettingsChangedEvent: "app-settings-changed-event",
inputDetectedEvent: "input-detected-event",
timerCompleteEvent: "timer-complete-event",
timerUpdatedEvent: "timer-updated-event"
})

/** user-defined constants **/



/** user-defined types **/

export type ActivitySettings = { 
/**
 * Whether activity tracking is enabled
 */
enabled: boolean; 
/**
 * Whether to track window changes (not just app switches)
 */
trackWindows: boolean; 
/**
 * Whether to track browser URLs
 */
trackBrowser: boolean }
export type AppInfo = { version: string; stage: Stage }
export type AppSettings = { appearance: AppearanceSettings; debug: DebugSettings; timer: TimerSettings; focusGoal: FocusGoalSettings; activity: ActivitySettings }
export type AppSettingsChangedEvent = AppSettings
export type AppearanceSettings = { theme: Theme }
export type DebugSettings = { enabled: boolean; cat: boolean; timerSpeed: number }
export type FocusGoalSettings = { 
/**
 * Daily focus goal in minutes (default: 120 = 2h)
 */
dailyGoalMinutes: number }
export type GetWindowActivitiesParams = { startedAfter: number; startedBefore: number; limit: number | null }
/**
 * Event emitted when user input is detected (throttled).
 */
export type InputDetectedEvent = InputType
/**
 * Type of input event detected.
 */
export type InputType = "keyboard" | "mouse"
export type Phase = "work" | "shortBreak" | "longBreak"
/**
 * Detailed DTO with events and computed stats.
 */
export type SessionDetailDto = { id: number; phase: Phase; status: SessionStatus; plannedSeconds: number; actualSeconds: number | null; startedAt: number; endedAt: number | null; events: SessionEventDto[]; stats: SessionStatsDto }
/**
 * Event data for events with extra fields.
 */
export type SessionEventDataDto = { seconds: number | null }
/**
 * Event DTO for frontend.
 */
export type SessionEventDto = { eventType: string; timestamp: number; 
/**
 * Extra data (e.g., seconds for Extended events)
 */
data: SessionEventDataDto | null }
/**
 * Computed stats for a session.
 */
export type SessionStatsDto = { pausedSeconds: number; extendedSeconds: number }
export type SessionStatus = "active" | "completed" | "cancelled"
/**
 * Summary DTO for session list views.
 */
export type SessionSummaryDto = { id: number; phase: Phase; status: SessionStatus; plannedSeconds: number; actualSeconds: number | null; startedAt: number; endedAt: number | null }
export type Stage = "dev" | "prod"
export type Theme = "light" | "dark" | "auto"
export type Timer = { status: TimerStatus; phase: Phase; totalSeconds: number; remainingSeconds: number; overtimeSeconds: number; sessionsCompleted: number; lastWorkSession: WorkSessionStats | null; speed: number }
export type TimerCompleteEvent = Phase
export type TimerSettings = { 
/**
 * Work duration in minutes
 */
workDurationMinutes: number; 
/**
 * Short break duration in minutes
 */
shortBreakMinutes: number; 
/**
 * Long break duration in minutes
 */
longBreakMinutes: number; 
/**
 * Number of work sessions before a long break
 */
sessionsBeforeLongBreak: number }
export type TimerStatus = "idle" | "running" | "paused"
export type TimerUpdatedEvent = Timer
export type WindowActivityDto = { appBundleId: string | null; appName: string | null; appIcon: string | null; appColor: string | null; windowTitle: string | null; browserUrl: string | null; startedAt: number; endedAt: number }
export type WorkSessionStats = { baseSeconds: number; extendedSeconds: number; overtimeSeconds: number; completedSeconds: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
