
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getAppInfo() : Promise<AppInfo> {
    return await TAURI_INVOKE("get_app_info");
},
async showMainWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_main_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showCatWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_cat_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showSettingsWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_settings_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showHistoryWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_history_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showHistoryWindowAtSession(sessionId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_history_window_at_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideMainWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_main_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideCatWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_cat_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideSettingsWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_settings_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideHistoryWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_history_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async quitApp() : Promise<void> {
    await TAURI_INVOKE("quit_app");
},
async getSettings() : Promise<AppSettings> {
    return await TAURI_INVOKE("get_settings");
},
async setSettings(settings: AppSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDataDirectoryPath() : Promise<string> {
    return await TAURI_INVOKE("get_data_directory_path");
},
async openDataDirectory() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_data_directory") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTimer() : Promise<TimerDto> {
    return await TAURI_INVOKE("get_timer");
},
async startTimer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseTimer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeTimer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetTimer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async skipTimer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("skip_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Finish the current session and reset timer.
 * Like reset, but marks session as completed instead of cancelled.
 */
async finishTimer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("finish_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTimerDuration(minutes: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_timer_duration", { minutes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get window activities within a time range.
 */
async getWindowActivities(params: GetWindowActivitiesParams) : Promise<Result<WindowActivityDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_window_activities", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTodayFocusSeconds() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_today_focus_seconds") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSessions(startedAfter: number, startedBefore: number, limit: number | null, minDurationSecs: number | null) : Promise<Result<SessionSummaryDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sessions", { startedAfter, startedBefore, limit, minDurationSecs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSession(sessionId: number) : Promise<Result<SessionDetailDto | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the most recent completed work session.
 */
async getLastWorkSession(minDurationSecs: number | null) : Promise<Result<SessionDetailDto | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_last_work_session", { minDurationSecs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if accessibility permission is granted.
 */
async isAccessibilityGranted() : Promise<boolean> {
    return await TAURI_INVOKE("is_accessibility_granted");
},
/**
 * Open System Settings to Accessibility pane.
 */
async openAccessibilitySettings() : Promise<void> {
    await TAURI_INVOKE("open_accessibility_settings");
},
/**
 * Check if input monitoring permission is granted.
 */
async isInputMonitoringGranted() : Promise<boolean> {
    return await TAURI_INVOKE("is_input_monitoring_granted");
},
/**
 * Open System Settings to Input Monitoring pane.
 */
async openInputMonitoringSettings() : Promise<void> {
    await TAURI_INVOKE("open_input_monitoring_settings");
},
/**
 * Search for apps and websites.
 */
async search(input: SearchInput) : Promise<Result<SearchResultDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Refresh the search cache (reloads apps from system).
 */
async refreshSearchCache() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_search_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Play a sound effect.
 */
async playSound(id: SoundId) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("play_sound", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTags() : Promise<Result<TagDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tags") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTag(id: number) : Promise<Result<TagDto | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tag", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createTag(name: string, color: string | null) : Promise<Result<TagDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_tag", { name, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTag(id: number, name: string, color: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_tag", { id, name, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTag(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_tag", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTagRestrictions(tagId: number) : Promise<Result<RestrictionDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tag_restrictions", { tagId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Upserts the app (created if new, found by bundle_id if exists).
 */
async addAppRestriction(tagId: number, action: RestrictionAction, bundleId: string, name: string | null, icon: string | null, color: string | null) : Promise<Result<RestrictionDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_app_restriction", { tagId, action, bundleId, name, icon, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Upserts the website (created if new, found by domain if exists).
 */
async addWebsiteRestriction(tagId: number, action: RestrictionAction, domain: string) : Promise<Result<RestrictionDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_website_restriction", { tagId, action, domain }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeRestriction(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_restriction", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSchedules() : Promise<Result<ScheduleDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_schedules") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSchedule(name: string, days: number[], startTime: string, endTime: string) : Promise<Result<ScheduleDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_schedule", { name, days, startTime, endTime }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSchedule(id: number, name: string, days: number[], startTime: string, endTime: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_schedule", { id, name, days, startTime, endTime }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSchedule(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_schedule", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addScheduleTag(scheduleId: number, tagId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_schedule_tag", { scheduleId, tagId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeScheduleTag(scheduleId: number, tagId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_schedule_tag", { scheduleId, tagId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getScheduleTags(scheduleId: number) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_schedule_tags", { scheduleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
appSettingsChangedEvent: AppSettingsChangedEvent,
inputDetectedEvent: InputDetectedEvent,
sessionCompletedEvent: SessionCompletedEvent,
timerUpdatedEvent: TimerUpdatedEvent
}>({
appSettingsChangedEvent: "app-settings-changed-event",
inputDetectedEvent: "input-detected-event",
sessionCompletedEvent: "session-completed-event",
timerUpdatedEvent: "timer-updated-event"
})

/** user-defined constants **/



/** user-defined types **/

export type ActivitySettings = { 
/**
 * Whether activity tracking is enabled
 */
enabled: boolean; 
/**
 * Whether to track window changes (not just app switches)
 */
trackWindows: boolean; 
/**
 * Whether to track browser URLs
 */
trackBrowser: boolean }
export type AppInfo = { version: string; stage: Stage }
export type AppSettings = { appearance: AppearanceSettings; debug: DebugSettings; timer: TimerSettings; focusGoal: FocusGoalSettings; activity: ActivitySettings }
export type AppSettingsChangedEvent = AppSettings
export type AppearanceSettings = { theme: Theme }
export type DebugSettings = { enabled: boolean; cat: boolean; timerSpeed: number }
export type FocusGoalSettings = { 
/**
 * Daily focus goal in minutes (default: 120 = 2h)
 */
dailyGoalMinutes: number }
export type GetWindowActivitiesParams = { startedAfter: number; startedBefore: number; limit: number | null }
/**
 * Event emitted when user input is detected (throttled).
 */
export type InputDetectedEvent = InputType
/**
 * Type of input event detected.
 */
export type InputType = "keyboard" | "mouse"
export type ItemType = "app" | "website"
export type Phase = "work" | "shortBreak" | "longBreak"
/**
 * Action for a restriction.
 */
export type RestrictionAction = "block" | "allow"
export type RestrictionDto = { id: number; tagId: number; action: RestrictionAction; appId: number | null; appBundleId: string | null; appName: string | null; appIcon: string | null; websiteId: number | null; websiteDomain: string | null; websiteName: string | null; websiteIcon: string | null }
export type ScheduleDto = { id: number; name: string; 
/**
 * Days of week (1 = Monday, 7 = Sunday)
 */
days: number[]; 
/**
 * Start time in HH:MM format
 */
startTime: string; 
/**
 * End time in HH:MM format
 */
endTime: string; createdAt: number }
export type SearchInput = { 
/**
 * Search query
 */
query: string; 
/**
 * Include installed apps (default: true)
 */
includeApps?: boolean; 
/**
 * Include websites (default: true)
 */
includeWebsites?: boolean; 
/**
 * Include icons - slower (default: false)
 */
includeIcons?: boolean; 
/**
 * Maximum results (default: 20)
 */
limit: number | null }
export type SearchResultDto = { 
/**
 * Unique identifier - bundleId for apps, domain for websites
 */
id: string; 
/**
 * Display name
 */
name: string; 
/**
 * Type of result
 */
itemType: ItemType; 
/**
 * Icon as base64 PNG data URL (apps) or favicon URL (websites)
 */
icon: string | null; 
/**
 * Brand color as hex string like "#5865F2" (apps only)
 */
color: string | null; 
/**
 * Match score (higher = better match)
 */
score: number }
/**
 * Event emitted when a session is completed.
 */
export type SessionCompletedEvent = SessionSummaryDto
export type SessionDetailDto = { id: number; phase: Phase; status: SessionStatus; plannedSeconds: number; actualSeconds: number | null; startedAt: number; endedAt: number | null; events: SessionEventDto[]; stats: SessionStatsDto }
export type SessionEventDataDto = { seconds: number | null }
export type SessionEventDto = { eventType: string; timestamp: number; 
/**
 * Extra data (e.g., seconds for Extended events)
 */
data: SessionEventDataDto | null }
/**
 * Computed stats for a session.
 */
export type SessionStatsDto = { pausedSeconds: number; extendedSeconds: number; overtimeSeconds: number }
export type SessionStatus = "active" | "completed" | "cancelled"
export type SessionSummaryDto = { id: number; phase: Phase; status: SessionStatus; plannedSeconds: number; actualSeconds: number | null; startedAt: number; endedAt: number | null }
export type SoundId = "tick" | "complete" | "meow"
export type Stage = "dev" | "prod"
export type TagDto = { id: number; name: string; color: string | null; createdAt: number }
export type Theme = "light" | "dark" | "auto"
export type TimerDto = { status: TimerStatus; phase: Phase; totalSeconds: number; remainingSeconds: number; overtimeSeconds: number; sessionsCompleted: number; speed: number }
export type TimerSettings = { 
/**
 * Work duration in minutes
 */
workDurationMinutes: number; 
/**
 * Short break duration in minutes
 */
shortBreakMinutes: number; 
/**
 * Long break duration in minutes
 */
longBreakMinutes: number; 
/**
 * Number of work sessions before a long break
 */
sessionsBeforeLongBreak: number }
export type TimerStatus = "idle" | "running" | "paused"
export type TimerUpdatedEvent = TimerDto
export type WindowActivityDto = { appBundleId: string | null; appName: string | null; appIcon: string | null; appColor: string | null; websiteDomain: string | null; websiteName: string | null; websiteIcon: string | null; websiteColor: string | null; windowTitle: string | null; browserUrl: string | null; startedAt: number; endedAt: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
