
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async showMainWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_main_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showCatWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_cat_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideMainWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_main_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideCatWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_cat_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async quitApp() : Promise<void> {
    await TAURI_INVOKE("quit_app");
},
async getSettings() : Promise<AppSettings> {
    return await TAURI_INVOKE("get_settings");
},
async setSettings(settings: AppSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDataDirectoryPath() : Promise<string> {
    return await TAURI_INVOKE("get_data_directory_path");
},
async openDataDirectory() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_data_directory") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTimer() : Promise<Timer> {
    return await TAURI_INVOKE("get_timer");
},
async startTimer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseTimer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeTimer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetTimer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async skipTimer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("skip_timer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTimerDuration(minutes: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_timer_duration", { minutes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTimerTags(sessionTagIds: number[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_timer_tags", { sessionTagIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cycleTimerSpeed() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cycle_timer_speed") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSessionTags() : Promise<Result<SessionTag[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session_tags") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSessionTagWithRules(id: number) : Promise<Result<SessionTagWithRules | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session_tag_with_rules", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSessionTag(name: string, color: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_session_tag", { name, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSessionTag(id: number, name: string, color: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_session_tag", { id, name, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSessionTag(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_session_tag", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addSessionTagRule(sessionTagId: number, appBundleId: string, appName: string | null) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_session_tag_rule", { sessionTagId, appBundleId, appName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSessionTagRule(ruleId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_session_tag_rule", { ruleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get window activities within a time range.
 */
async getWindowActivities(params: GetWindowActivitiesParams) : Promise<Result<WindowActivityDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_window_activities", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if accessibility permission is granted.
 */
async isAccessibilityGranted() : Promise<boolean> {
    return await TAURI_INVOKE("is_accessibility_granted");
},
/**
 * Open System Settings to Accessibility pane.
 */
async openAccessibilitySettings() : Promise<void> {
    await TAURI_INVOKE("open_accessibility_settings");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
appSettingsChangedEvent: AppSettingsChangedEvent,
inputDetectedEvent: InputDetectedEvent,
timerCompleteEvent: TimerCompleteEvent,
timerTickEvent: TimerTickEvent
}>({
appSettingsChangedEvent: "app-settings-changed-event",
inputDetectedEvent: "input-detected-event",
timerCompleteEvent: "timer-complete-event",
timerTickEvent: "timer-tick-event"
})

/** user-defined constants **/



/** user-defined types **/

export type AppSettings = { debug: boolean; 
/**
 * Work duration in minutes
 */
workDurationMinutes: number; 
/**
 * Short break duration in minutes
 */
shortBreakMinutes: number; 
/**
 * Long break duration in minutes
 */
longBreakMinutes: number; 
/**
 * Number of work sessions before a long break
 */
sessionsBeforeLongBreak: number }
export type AppSettingsChangedEvent = AppSettings
export type GetWindowActivitiesParams = { startedAfter: number; startedBefore: number; limit: number | null }
/**
 * Event emitted when user input is detected (throttled).
 */
export type InputDetectedEvent = InputType
/**
 * Type of input event detected.
 */
export type InputType = "keyboard" | "mouse"
export type SessionTag = { id: number; name: string; color: string }
export type SessionTagRule = { id: number; sessionTagId: number; appBundleId: string; appName: string | null }
export type SessionTagWithRules = { id: number; name: string; color: string; rules: SessionTagRule[] }
export type Timer = { status: TimerStatus; phase: TimerPhase; totalSeconds: number; remainingSeconds: number; 
/**
 * Counts up after timer hits zero
 */
overtimeSeconds: number; 
/**
 * Session tag IDs applied to current session
 */
sessionTagIds: number[]; sessionsCompleted: number; 
/**
 * Base work duration from settings
 */
baseWorkSeconds: number; 
/**
 * Work done before current segment (for multi-extension tracking)
 */
accumulatedWorkSeconds: number; 
/**
 * Time added via wheel extensions this session
 */
totalExtendedSeconds: number; 
/**
 * Stats from last work session (shown during breaks)
 */
lastWorkSession: WorkSessionStats | null; 
/**
 * Debug: speed multiplier
 */
speed: number }
/**
 * Event emitted when timer phase completes.
 */
export type TimerCompleteEvent = TimerPhase
export type TimerPhase = "work" | "shortBreak" | "longBreak"
export type TimerStatus = "idle" | "running" | "paused"
/**
 * Event emitted every second while timer is running.
 */
export type TimerTickEvent = Timer
export type WindowActivityDto = { appBundleId: string | null; appName: string | null; appIcon: string | null; windowTitle: string | null; browserUrl: string | null; startedAt: number; endedAt: number }
/**
 * Stats from the last completed work session (shown during breaks).
 */
export type WorkSessionStats = { 
/**
 * Original work duration from settings
 */
baseSeconds: number; 
/**
 * Time added via wheel adjustment
 */
extendedSeconds: number; 
/**
 * Time spent after timer hit zero (unplanned)
 */
overtimeSeconds: number; 
/**
 * Total time completed (base + extended + overtime)
 */
completedSeconds: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
