/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WindowSettingsRouteRouteImport } from './routes/window.settings/route'
import { Route as WindowMainRouteRouteImport } from './routes/window.main/route'
import { Route as WindowCatRouteRouteImport } from './routes/window.cat/route'
import { Route as WindowSettingsIndexRouteImport } from './routes/window.settings/index'
import { Route as WindowMainIndexRouteImport } from './routes/window.main/index'
import { Route as WindowCatIndexRouteImport } from './routes/window.cat/index'
import { Route as WindowSettingsGeneralIndexRouteImport } from './routes/window.settings.general/index'
import { Route as WindowSettingsDeveloperIndexRouteImport } from './routes/window.settings.developer/index'

const WindowSettingsRouteRoute = WindowSettingsRouteRouteImport.update({
  id: '/window/settings',
  path: '/window/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowMainRouteRoute = WindowMainRouteRouteImport.update({
  id: '/window/main',
  path: '/window/main',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowCatRouteRoute = WindowCatRouteRouteImport.update({
  id: '/window/cat',
  path: '/window/cat',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowSettingsIndexRoute = WindowSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WindowSettingsRouteRoute,
} as any)
const WindowMainIndexRoute = WindowMainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WindowMainRouteRoute,
} as any)
const WindowCatIndexRoute = WindowCatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WindowCatRouteRoute,
} as any)
const WindowSettingsGeneralIndexRoute =
  WindowSettingsGeneralIndexRouteImport.update({
    id: '/general/',
    path: '/general/',
    getParentRoute: () => WindowSettingsRouteRoute,
  } as any)
const WindowSettingsDeveloperIndexRoute =
  WindowSettingsDeveloperIndexRouteImport.update({
    id: '/developer/',
    path: '/developer/',
    getParentRoute: () => WindowSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/window/cat': typeof WindowCatRouteRouteWithChildren
  '/window/main': typeof WindowMainRouteRouteWithChildren
  '/window/settings': typeof WindowSettingsRouteRouteWithChildren
  '/window/cat/': typeof WindowCatIndexRoute
  '/window/main/': typeof WindowMainIndexRoute
  '/window/settings/': typeof WindowSettingsIndexRoute
  '/window/settings/developer': typeof WindowSettingsDeveloperIndexRoute
  '/window/settings/general': typeof WindowSettingsGeneralIndexRoute
}
export interface FileRoutesByTo {
  '/window/cat': typeof WindowCatIndexRoute
  '/window/main': typeof WindowMainIndexRoute
  '/window/settings': typeof WindowSettingsIndexRoute
  '/window/settings/developer': typeof WindowSettingsDeveloperIndexRoute
  '/window/settings/general': typeof WindowSettingsGeneralIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/window/cat': typeof WindowCatRouteRouteWithChildren
  '/window/main': typeof WindowMainRouteRouteWithChildren
  '/window/settings': typeof WindowSettingsRouteRouteWithChildren
  '/window/cat/': typeof WindowCatIndexRoute
  '/window/main/': typeof WindowMainIndexRoute
  '/window/settings/': typeof WindowSettingsIndexRoute
  '/window/settings/developer/': typeof WindowSettingsDeveloperIndexRoute
  '/window/settings/general/': typeof WindowSettingsGeneralIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/window/cat'
    | '/window/main'
    | '/window/settings'
    | '/window/cat/'
    | '/window/main/'
    | '/window/settings/'
    | '/window/settings/developer'
    | '/window/settings/general'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/window/cat'
    | '/window/main'
    | '/window/settings'
    | '/window/settings/developer'
    | '/window/settings/general'
  id:
    | '__root__'
    | '/window/cat'
    | '/window/main'
    | '/window/settings'
    | '/window/cat/'
    | '/window/main/'
    | '/window/settings/'
    | '/window/settings/developer/'
    | '/window/settings/general/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WindowCatRouteRoute: typeof WindowCatRouteRouteWithChildren
  WindowMainRouteRoute: typeof WindowMainRouteRouteWithChildren
  WindowSettingsRouteRoute: typeof WindowSettingsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/window/settings': {
      id: '/window/settings'
      path: '/window/settings'
      fullPath: '/window/settings'
      preLoaderRoute: typeof WindowSettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window/main': {
      id: '/window/main'
      path: '/window/main'
      fullPath: '/window/main'
      preLoaderRoute: typeof WindowMainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window/cat': {
      id: '/window/cat'
      path: '/window/cat'
      fullPath: '/window/cat'
      preLoaderRoute: typeof WindowCatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window/settings/': {
      id: '/window/settings/'
      path: '/'
      fullPath: '/window/settings/'
      preLoaderRoute: typeof WindowSettingsIndexRouteImport
      parentRoute: typeof WindowSettingsRouteRoute
    }
    '/window/main/': {
      id: '/window/main/'
      path: '/'
      fullPath: '/window/main/'
      preLoaderRoute: typeof WindowMainIndexRouteImport
      parentRoute: typeof WindowMainRouteRoute
    }
    '/window/cat/': {
      id: '/window/cat/'
      path: '/'
      fullPath: '/window/cat/'
      preLoaderRoute: typeof WindowCatIndexRouteImport
      parentRoute: typeof WindowCatRouteRoute
    }
    '/window/settings/general/': {
      id: '/window/settings/general/'
      path: '/general'
      fullPath: '/window/settings/general'
      preLoaderRoute: typeof WindowSettingsGeneralIndexRouteImport
      parentRoute: typeof WindowSettingsRouteRoute
    }
    '/window/settings/developer/': {
      id: '/window/settings/developer/'
      path: '/developer'
      fullPath: '/window/settings/developer'
      preLoaderRoute: typeof WindowSettingsDeveloperIndexRouteImport
      parentRoute: typeof WindowSettingsRouteRoute
    }
  }
}

interface WindowCatRouteRouteChildren {
  WindowCatIndexRoute: typeof WindowCatIndexRoute
}

const WindowCatRouteRouteChildren: WindowCatRouteRouteChildren = {
  WindowCatIndexRoute: WindowCatIndexRoute,
}

const WindowCatRouteRouteWithChildren = WindowCatRouteRoute._addFileChildren(
  WindowCatRouteRouteChildren,
)

interface WindowMainRouteRouteChildren {
  WindowMainIndexRoute: typeof WindowMainIndexRoute
}

const WindowMainRouteRouteChildren: WindowMainRouteRouteChildren = {
  WindowMainIndexRoute: WindowMainIndexRoute,
}

const WindowMainRouteRouteWithChildren = WindowMainRouteRoute._addFileChildren(
  WindowMainRouteRouteChildren,
)

interface WindowSettingsRouteRouteChildren {
  WindowSettingsIndexRoute: typeof WindowSettingsIndexRoute
  WindowSettingsDeveloperIndexRoute: typeof WindowSettingsDeveloperIndexRoute
  WindowSettingsGeneralIndexRoute: typeof WindowSettingsGeneralIndexRoute
}

const WindowSettingsRouteRouteChildren: WindowSettingsRouteRouteChildren = {
  WindowSettingsIndexRoute: WindowSettingsIndexRoute,
  WindowSettingsDeveloperIndexRoute: WindowSettingsDeveloperIndexRoute,
  WindowSettingsGeneralIndexRoute: WindowSettingsGeneralIndexRoute,
}

const WindowSettingsRouteRouteWithChildren =
  WindowSettingsRouteRoute._addFileChildren(WindowSettingsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  WindowCatRouteRoute: WindowCatRouteRouteWithChildren,
  WindowMainRouteRoute: WindowMainRouteRouteWithChildren,
  WindowSettingsRouteRoute: WindowSettingsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
