/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WindowSettingsRouteRouteImport } from './routes/window.settings/route'
import { Route as WindowMainRouteRouteImport } from './routes/window.main/route'
import { Route as WindowHistoryRouteRouteImport } from './routes/window.history/route'
import { Route as WindowCatRouteRouteImport } from './routes/window.cat/route'
import { Route as WindowSettingsIndexRouteImport } from './routes/window.settings/index'
import { Route as WindowMainIndexRouteImport } from './routes/window.main/index'
import { Route as WindowHistoryIndexRouteImport } from './routes/window.history/index'
import { Route as WindowCatIndexRouteImport } from './routes/window.cat/index'
import { Route as WindowSettingsTimerIndexRouteImport } from './routes/window.settings.timer/index'
import { Route as WindowSettingsGoalsIndexRouteImport } from './routes/window.settings.goals/index'
import { Route as WindowSettingsDeveloperIndexRouteImport } from './routes/window.settings.developer/index'
import { Route as WindowSettingsBlockIndexRouteImport } from './routes/window.settings.block/index'
import { Route as WindowSettingsAppIndexRouteImport } from './routes/window.settings.app/index'
import { Route as WindowSettingsActivityIndexRouteImport } from './routes/window.settings.activity/index'
import { Route as WindowMainSplashIndexRouteImport } from './routes/window.main.splash/index'
import { Route as WindowHistorySessionIdIndexRouteImport } from './routes/window.history.$sessionId/index'

const WindowSettingsRouteRoute = WindowSettingsRouteRouteImport.update({
  id: '/window/settings',
  path: '/window/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowMainRouteRoute = WindowMainRouteRouteImport.update({
  id: '/window/main',
  path: '/window/main',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowHistoryRouteRoute = WindowHistoryRouteRouteImport.update({
  id: '/window/history',
  path: '/window/history',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowCatRouteRoute = WindowCatRouteRouteImport.update({
  id: '/window/cat',
  path: '/window/cat',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowSettingsIndexRoute = WindowSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WindowSettingsRouteRoute,
} as any)
const WindowMainIndexRoute = WindowMainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WindowMainRouteRoute,
} as any)
const WindowHistoryIndexRoute = WindowHistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WindowHistoryRouteRoute,
} as any)
const WindowCatIndexRoute = WindowCatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WindowCatRouteRoute,
} as any)
const WindowSettingsTimerIndexRoute =
  WindowSettingsTimerIndexRouteImport.update({
    id: '/timer/',
    path: '/timer/',
    getParentRoute: () => WindowSettingsRouteRoute,
  } as any)
const WindowSettingsGoalsIndexRoute =
  WindowSettingsGoalsIndexRouteImport.update({
    id: '/goals/',
    path: '/goals/',
    getParentRoute: () => WindowSettingsRouteRoute,
  } as any)
const WindowSettingsDeveloperIndexRoute =
  WindowSettingsDeveloperIndexRouteImport.update({
    id: '/developer/',
    path: '/developer/',
    getParentRoute: () => WindowSettingsRouteRoute,
  } as any)
const WindowSettingsBlockIndexRoute =
  WindowSettingsBlockIndexRouteImport.update({
    id: '/block/',
    path: '/block/',
    getParentRoute: () => WindowSettingsRouteRoute,
  } as any)
const WindowSettingsAppIndexRoute = WindowSettingsAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => WindowSettingsRouteRoute,
} as any)
const WindowSettingsActivityIndexRoute =
  WindowSettingsActivityIndexRouteImport.update({
    id: '/activity/',
    path: '/activity/',
    getParentRoute: () => WindowSettingsRouteRoute,
  } as any)
const WindowMainSplashIndexRoute = WindowMainSplashIndexRouteImport.update({
  id: '/splash/',
  path: '/splash/',
  getParentRoute: () => WindowMainRouteRoute,
} as any)
const WindowHistorySessionIdIndexRoute =
  WindowHistorySessionIdIndexRouteImport.update({
    id: '/$sessionId/',
    path: '/$sessionId/',
    getParentRoute: () => WindowHistoryRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/window/cat': typeof WindowCatRouteRouteWithChildren
  '/window/history': typeof WindowHistoryRouteRouteWithChildren
  '/window/main': typeof WindowMainRouteRouteWithChildren
  '/window/settings': typeof WindowSettingsRouteRouteWithChildren
  '/window/cat/': typeof WindowCatIndexRoute
  '/window/history/': typeof WindowHistoryIndexRoute
  '/window/main/': typeof WindowMainIndexRoute
  '/window/settings/': typeof WindowSettingsIndexRoute
  '/window/history/$sessionId': typeof WindowHistorySessionIdIndexRoute
  '/window/main/splash': typeof WindowMainSplashIndexRoute
  '/window/settings/activity': typeof WindowSettingsActivityIndexRoute
  '/window/settings/app': typeof WindowSettingsAppIndexRoute
  '/window/settings/block': typeof WindowSettingsBlockIndexRoute
  '/window/settings/developer': typeof WindowSettingsDeveloperIndexRoute
  '/window/settings/goals': typeof WindowSettingsGoalsIndexRoute
  '/window/settings/timer': typeof WindowSettingsTimerIndexRoute
}
export interface FileRoutesByTo {
  '/window/cat': typeof WindowCatIndexRoute
  '/window/history': typeof WindowHistoryIndexRoute
  '/window/main': typeof WindowMainIndexRoute
  '/window/settings': typeof WindowSettingsIndexRoute
  '/window/history/$sessionId': typeof WindowHistorySessionIdIndexRoute
  '/window/main/splash': typeof WindowMainSplashIndexRoute
  '/window/settings/activity': typeof WindowSettingsActivityIndexRoute
  '/window/settings/app': typeof WindowSettingsAppIndexRoute
  '/window/settings/block': typeof WindowSettingsBlockIndexRoute
  '/window/settings/developer': typeof WindowSettingsDeveloperIndexRoute
  '/window/settings/goals': typeof WindowSettingsGoalsIndexRoute
  '/window/settings/timer': typeof WindowSettingsTimerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/window/cat': typeof WindowCatRouteRouteWithChildren
  '/window/history': typeof WindowHistoryRouteRouteWithChildren
  '/window/main': typeof WindowMainRouteRouteWithChildren
  '/window/settings': typeof WindowSettingsRouteRouteWithChildren
  '/window/cat/': typeof WindowCatIndexRoute
  '/window/history/': typeof WindowHistoryIndexRoute
  '/window/main/': typeof WindowMainIndexRoute
  '/window/settings/': typeof WindowSettingsIndexRoute
  '/window/history/$sessionId/': typeof WindowHistorySessionIdIndexRoute
  '/window/main/splash/': typeof WindowMainSplashIndexRoute
  '/window/settings/activity/': typeof WindowSettingsActivityIndexRoute
  '/window/settings/app/': typeof WindowSettingsAppIndexRoute
  '/window/settings/block/': typeof WindowSettingsBlockIndexRoute
  '/window/settings/developer/': typeof WindowSettingsDeveloperIndexRoute
  '/window/settings/goals/': typeof WindowSettingsGoalsIndexRoute
  '/window/settings/timer/': typeof WindowSettingsTimerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/window/cat'
    | '/window/history'
    | '/window/main'
    | '/window/settings'
    | '/window/cat/'
    | '/window/history/'
    | '/window/main/'
    | '/window/settings/'
    | '/window/history/$sessionId'
    | '/window/main/splash'
    | '/window/settings/activity'
    | '/window/settings/app'
    | '/window/settings/block'
    | '/window/settings/developer'
    | '/window/settings/goals'
    | '/window/settings/timer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/window/cat'
    | '/window/history'
    | '/window/main'
    | '/window/settings'
    | '/window/history/$sessionId'
    | '/window/main/splash'
    | '/window/settings/activity'
    | '/window/settings/app'
    | '/window/settings/block'
    | '/window/settings/developer'
    | '/window/settings/goals'
    | '/window/settings/timer'
  id:
    | '__root__'
    | '/window/cat'
    | '/window/history'
    | '/window/main'
    | '/window/settings'
    | '/window/cat/'
    | '/window/history/'
    | '/window/main/'
    | '/window/settings/'
    | '/window/history/$sessionId/'
    | '/window/main/splash/'
    | '/window/settings/activity/'
    | '/window/settings/app/'
    | '/window/settings/block/'
    | '/window/settings/developer/'
    | '/window/settings/goals/'
    | '/window/settings/timer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WindowCatRouteRoute: typeof WindowCatRouteRouteWithChildren
  WindowHistoryRouteRoute: typeof WindowHistoryRouteRouteWithChildren
  WindowMainRouteRoute: typeof WindowMainRouteRouteWithChildren
  WindowSettingsRouteRoute: typeof WindowSettingsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/window/settings': {
      id: '/window/settings'
      path: '/window/settings'
      fullPath: '/window/settings'
      preLoaderRoute: typeof WindowSettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window/main': {
      id: '/window/main'
      path: '/window/main'
      fullPath: '/window/main'
      preLoaderRoute: typeof WindowMainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window/history': {
      id: '/window/history'
      path: '/window/history'
      fullPath: '/window/history'
      preLoaderRoute: typeof WindowHistoryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window/cat': {
      id: '/window/cat'
      path: '/window/cat'
      fullPath: '/window/cat'
      preLoaderRoute: typeof WindowCatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window/settings/': {
      id: '/window/settings/'
      path: '/'
      fullPath: '/window/settings/'
      preLoaderRoute: typeof WindowSettingsIndexRouteImport
      parentRoute: typeof WindowSettingsRouteRoute
    }
    '/window/main/': {
      id: '/window/main/'
      path: '/'
      fullPath: '/window/main/'
      preLoaderRoute: typeof WindowMainIndexRouteImport
      parentRoute: typeof WindowMainRouteRoute
    }
    '/window/history/': {
      id: '/window/history/'
      path: '/'
      fullPath: '/window/history/'
      preLoaderRoute: typeof WindowHistoryIndexRouteImport
      parentRoute: typeof WindowHistoryRouteRoute
    }
    '/window/cat/': {
      id: '/window/cat/'
      path: '/'
      fullPath: '/window/cat/'
      preLoaderRoute: typeof WindowCatIndexRouteImport
      parentRoute: typeof WindowCatRouteRoute
    }
    '/window/settings/timer/': {
      id: '/window/settings/timer/'
      path: '/timer'
      fullPath: '/window/settings/timer'
      preLoaderRoute: typeof WindowSettingsTimerIndexRouteImport
      parentRoute: typeof WindowSettingsRouteRoute
    }
    '/window/settings/goals/': {
      id: '/window/settings/goals/'
      path: '/goals'
      fullPath: '/window/settings/goals'
      preLoaderRoute: typeof WindowSettingsGoalsIndexRouteImport
      parentRoute: typeof WindowSettingsRouteRoute
    }
    '/window/settings/developer/': {
      id: '/window/settings/developer/'
      path: '/developer'
      fullPath: '/window/settings/developer'
      preLoaderRoute: typeof WindowSettingsDeveloperIndexRouteImport
      parentRoute: typeof WindowSettingsRouteRoute
    }
    '/window/settings/block/': {
      id: '/window/settings/block/'
      path: '/block'
      fullPath: '/window/settings/block'
      preLoaderRoute: typeof WindowSettingsBlockIndexRouteImport
      parentRoute: typeof WindowSettingsRouteRoute
    }
    '/window/settings/app/': {
      id: '/window/settings/app/'
      path: '/app'
      fullPath: '/window/settings/app'
      preLoaderRoute: typeof WindowSettingsAppIndexRouteImport
      parentRoute: typeof WindowSettingsRouteRoute
    }
    '/window/settings/activity/': {
      id: '/window/settings/activity/'
      path: '/activity'
      fullPath: '/window/settings/activity'
      preLoaderRoute: typeof WindowSettingsActivityIndexRouteImport
      parentRoute: typeof WindowSettingsRouteRoute
    }
    '/window/main/splash/': {
      id: '/window/main/splash/'
      path: '/splash'
      fullPath: '/window/main/splash'
      preLoaderRoute: typeof WindowMainSplashIndexRouteImport
      parentRoute: typeof WindowMainRouteRoute
    }
    '/window/history/$sessionId/': {
      id: '/window/history/$sessionId/'
      path: '/$sessionId'
      fullPath: '/window/history/$sessionId'
      preLoaderRoute: typeof WindowHistorySessionIdIndexRouteImport
      parentRoute: typeof WindowHistoryRouteRoute
    }
  }
}

interface WindowCatRouteRouteChildren {
  WindowCatIndexRoute: typeof WindowCatIndexRoute
}

const WindowCatRouteRouteChildren: WindowCatRouteRouteChildren = {
  WindowCatIndexRoute: WindowCatIndexRoute,
}

const WindowCatRouteRouteWithChildren = WindowCatRouteRoute._addFileChildren(
  WindowCatRouteRouteChildren,
)

interface WindowHistoryRouteRouteChildren {
  WindowHistoryIndexRoute: typeof WindowHistoryIndexRoute
  WindowHistorySessionIdIndexRoute: typeof WindowHistorySessionIdIndexRoute
}

const WindowHistoryRouteRouteChildren: WindowHistoryRouteRouteChildren = {
  WindowHistoryIndexRoute: WindowHistoryIndexRoute,
  WindowHistorySessionIdIndexRoute: WindowHistorySessionIdIndexRoute,
}

const WindowHistoryRouteRouteWithChildren =
  WindowHistoryRouteRoute._addFileChildren(WindowHistoryRouteRouteChildren)

interface WindowMainRouteRouteChildren {
  WindowMainIndexRoute: typeof WindowMainIndexRoute
  WindowMainSplashIndexRoute: typeof WindowMainSplashIndexRoute
}

const WindowMainRouteRouteChildren: WindowMainRouteRouteChildren = {
  WindowMainIndexRoute: WindowMainIndexRoute,
  WindowMainSplashIndexRoute: WindowMainSplashIndexRoute,
}

const WindowMainRouteRouteWithChildren = WindowMainRouteRoute._addFileChildren(
  WindowMainRouteRouteChildren,
)

interface WindowSettingsRouteRouteChildren {
  WindowSettingsIndexRoute: typeof WindowSettingsIndexRoute
  WindowSettingsActivityIndexRoute: typeof WindowSettingsActivityIndexRoute
  WindowSettingsAppIndexRoute: typeof WindowSettingsAppIndexRoute
  WindowSettingsBlockIndexRoute: typeof WindowSettingsBlockIndexRoute
  WindowSettingsDeveloperIndexRoute: typeof WindowSettingsDeveloperIndexRoute
  WindowSettingsGoalsIndexRoute: typeof WindowSettingsGoalsIndexRoute
  WindowSettingsTimerIndexRoute: typeof WindowSettingsTimerIndexRoute
}

const WindowSettingsRouteRouteChildren: WindowSettingsRouteRouteChildren = {
  WindowSettingsIndexRoute: WindowSettingsIndexRoute,
  WindowSettingsActivityIndexRoute: WindowSettingsActivityIndexRoute,
  WindowSettingsAppIndexRoute: WindowSettingsAppIndexRoute,
  WindowSettingsBlockIndexRoute: WindowSettingsBlockIndexRoute,
  WindowSettingsDeveloperIndexRoute: WindowSettingsDeveloperIndexRoute,
  WindowSettingsGoalsIndexRoute: WindowSettingsGoalsIndexRoute,
  WindowSettingsTimerIndexRoute: WindowSettingsTimerIndexRoute,
}

const WindowSettingsRouteRouteWithChildren =
  WindowSettingsRouteRoute._addFileChildren(WindowSettingsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  WindowCatRouteRoute: WindowCatRouteRouteWithChildren,
  WindowHistoryRouteRoute: WindowHistoryRouteRouteWithChildren,
  WindowMainRouteRoute: WindowMainRouteRouteWithChildren,
  WindowSettingsRouteRoute: WindowSettingsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
